export default (
  '<div class="viewer-container" touch-action="none">'
    + '<div class="viewer-mega-gallery">'
      + '<div class="viewer-mega-gallery-body"></div>'
      + '<div role="button" class="viewer-fixed viewer-button viewer-close js-close-mega-gallery"></div>'
        + '<div class="viewer-footer viewer-footer-fixed">'
          + '<div class="viewer-toolbar">'
            + '<ul>'
              + '<li class="viewer-with-text viewer-reset-btn js-reset-btn"><span>сбросить</span></li>'
            + '</ul>'
          + '</div>'
        + '</div>'
      + '</div>'
    + '<div class="viewer-canvas"></div>'
    + '<div class="viewer-footer">'
      + '<div class="viewer-title"></div>'
      + '<div class="viewer-js-toolbar viewer-toolbar"></div>'
      + '<div class="viewer-navbar">'
        + '<ul class="viewer-list"></ul>'
      + '</div>'
    + '</div>'
    + '<div class="viewer-tooltip"></div>'
    + '<div role="button" class="viewer-button viewer-js-button" data-viewer-action="mix"></div>'
    + '<div class="viewer-player"></div>'
  + '</div>'
);
